"""Generate synthetic Gamry DTA files for testing the toolkit.

The spectra mimic mild steel in 1 M HCl with increasing inhibitor
concentration. They are simulated, not measured.
"""
from pathlib import Path
import sys

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from eistool.circuits import Circuit  # noqa: E402

OUT = Path(__file__).parent / "data"

SYSTEMS = [
    ("blank.DTA", "R0-p(R1,CPE1)", [1.8, 42.0, 3.2e-4, 0.82], -0.472, False),
    ("inhibitor_0.1mM.DTA", "R0-p(R1,CPE1)", [1.9, 150.0, 1.4e-4, 0.85], -0.468, False),
    ("inhibitor_1mM.DTA", "R0-p(R1,CPE1)", [1.8, 420.0, 7.0e-5, 0.87], -0.461, False),
    ("inhibitor_5mM.DTA", "R0-p(CPE1,R1-p(R2,CPE2))", [2.0, 2.0e-5, 0.90, 60.0, 780.0, 3.5e-5, 0.78], -0.455, True),
]

HEADER = """EXPLAIN
TAG\tEISPOT
TITLE\tLABEL\tPotentiostatic EIS {title}\tTest &Identifier
DATE\tLABEL\t9/24/2026\tDate
TIME\tLABEL\t10:{minute:02d}:00\tTime
NOTES\tNOTES\t1\t&Notes...
\tSynthetic example data generated by make_example_data.py
PSTAT\tPSTAT\tREF600-00000\tPotentiostat
VDC\tPOTEN\t{zero}\tT\tDC &Voltage (V)
FREQINIT\tQUANT\t{fi}\t&Initial Freq. (Hz)
FREQFINAL\tQUANT\t{ff}\t&Final Freq. (Hz)
PTSPERDEC\tQUANT\t{ppd}\t&Points/decade
VACAMPL\tQUANT\t{vac}\tAC &Voltage (mV rms)
AREA\tQUANT\t{area}\t&Area (cm^2)
EOC\tQUANT\t{eoc}\tOpen Circuit (V)
OCVCURVE\tTABLE\t5
\tPt\tT\tVf\tVm\tAch\tOver\tTemp
\t#\ts\tV vs. Ref.\tV\tV\tbits\tdeg C
"""


def fmt(x, comma):
    s = f"{x:.6E}"
    return s.replace(".", ",") if comma else s


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(42)
    freq = np.logspace(5, -2, 71)
    for k, (fname, circ, params, eoc, comma) in enumerate(SYSTEMS):
        z = Circuit(circ).impedance(params, freq)
        noise = 0.004 * np.abs(z)
        z = z + noise * (rng.standard_normal(len(z)) + 1j * rng.standard_normal(len(z)))
        f = lambda x: fmt(x, comma)  # noqa: E731
        txt = HEADER.format(title=fname, minute=k * 7, zero=f(0.0), fi=f(1e5), ff=f(1e-2),
                            ppd=f(10), vac=f(10), area=f(1.0), eoc=f(eoc))
        for i in range(5):
            v = eoc + 0.0005 * rng.standard_normal()
            txt += f"\t{i}\t{f(i * 0.5)}\t{f(v)}\t{f(v)}\t{f(0.0)}\t...........\t{f(25.0)}\n"
        txt += "ZCURVE\tTABLE\n"
        txt += "\tPt\tTime\tFreq\tZreal\tZimag\tZsig\tZmod\tZphz\tIdc\tVdc\tIERange\n"
        txt += "\t#\ts\tHz\tohm\tohm\tV\tohm\t°\tA\tV\t#\n"
        t = 0.0
        for i, (fr, zz) in enumerate(zip(freq, z)):
            t += max(1.0, 2.0 / fr)
            txt += "\t" + "\t".join([
                str(i), f(t), f(fr), f(zz.real), f(zz.imag), f(1.0), f(abs(zz)),
                f(np.degrees(np.angle(zz))), f(1e-7), f(eoc), "6"]) + "\n"
        txt += "EXPERIMENTABORTED\tTOGGLE\tF\tExperiment Aborted\n"
        (OUT / fname).write_bytes(txt.replace("\n", "\r\n").encode("cp1252"))
        print("wrote", OUT / fname, "(decimal comma)" if comma else "")


if __name__ == "__main__":
    main()
