"""Generate the synthetic Gamry DTA files used as examples and in the tests.

Two simulated (not measured) datasets:

inhibitor/  Mild steel in 1 M HCl with increasing inhibitor concentration.
            Low impedance (tens to hundreds of Ω cm²), 1 cm² electrode,
            100 kHz to 10 mHz at 10 points/decade. One file uses decimal
            commas (European Windows locale).

coating/    Epoxy-coated steel in 3.5 % NaCl over 30 days of immersion.
            High impedance (up to ~10 GΩ cm²), 3.14 cm² electrode stored in the
            DTA header, 100 kHz to 10 mHz at 7 points/decade. A second time
            constant (corrosion under the coating) appears after 7 days.
            The files deliberately vary the Gamry format: UTF-8 with BOM and
            LF line ends, a galvanostatic (EISGALV) header, no OCV block, a
            table row count on the ZCURVE line, and a file name with spaces.
"""
from pathlib import Path
import sys

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from eistool.circuits import Circuit  # noqa: E402

HERE = Path(__file__).parent

ONE_TC = "R0-p(CPE2,R2)"
TWO_TC = "R0-p(CPE2,R2-p(R1,CPE1))"

# name, circuit, params (area-normalised, Ω cm²), Eoc (V), options
INHIBITOR = [
    ("blank.DTA", "R0-p(R1,CPE1)", [1.8, 42.0, 3.2e-4, 0.82], -0.472, {}),
    ("inhibitor_0.1mM.DTA", "R0-p(R1,CPE1)", [1.9, 150.0, 1.4e-4, 0.85], -0.468, {}),
    ("inhibitor_1mM.DTA", "R0-p(R1,CPE1)", [1.8, 420.0, 7.0e-5, 0.87], -0.461, {}),
    ("inhibitor_5mM.DTA", TWO_TC, [2.0, 2.0e-5, 0.90, 60.0, 780.0, 3.5e-5, 0.78], -0.455,
     {"comma": True}),
]

COATING_AREA = 3.14  # cm², 20 mm diameter cell
# TWO_TC parameter order: R0, CPE2_Q, CPE2_n, R2, R1, CPE1_Q, CPE1_n
#   CPE2/R2 = coating capacitance / pore resistance, CPE1/R1 = double layer / charge transfer
COATING = [
    ("epoxy_1h.DTA", ONE_TC, [45.0, 1.5e-9, 0.95, 4.0e9], -0.312, {}),
    ("epoxy_24h.DTA", ONE_TC, [45.0, 3.2e-9, 0.93, 2.5e8], -0.405,
     {"encoding": "utf-8-sig", "eol": "\n"}),
    ("epoxy 7 days.DTA", TWO_TC, [45.0, 6.0e-9, 0.90, 8.0e6, 5.0e6, 1.5e-6, 0.75], -0.548,
     {"tag": "EISGALV", "ocv": False, "rowcount": True}),
    ("epoxy_30d.DTA", TWO_TC, [45.0, 1.2e-8, 0.88, 3.0e5, 2.5e6, 1.8e-5, 0.66], -0.611,
     {"encoding": "utf-8", "eol": "\n", "rowcount": True}),
]


def _fmt(x, comma):
    s = f"{x:.6E}"
    return s.replace(".", ",") if comma else s


def write_dta(path: Path, freq, z_ohm, eoc, rng, *, area=1.0, comma=False, tag="EISPOT",
              encoding="cp1252", eol="\r\n", ocv=True, rowcount=False, minute=0, ppd=10):
    f = lambda x: _fmt(x, comma)  # noqa: E731
    title = "Galvanostatic EIS" if tag == "EISGALV" else "Potentiostatic EIS"
    lines = [
        "EXPLAIN",
        f"TAG\t{tag}",
        f"TITLE\tLABEL\t{title} {path.stem}\tTest &Identifier",
        "DATE\tLABEL\t9/24/2026\tDate",
        f"TIME\tLABEL\t10:{minute:02d}:00\tTime",
        "NOTES\tNOTES\t2\t&Notes...",
        "\tSynthetic example data generated by make_example_data.py",
        "\tNot a real measurement",
        "PSTAT\tPSTAT\tREF600-00000\tPotentiostat",
    ]
    if tag == "EISGALV":
        lines += [f"IDC\tQUANT\t{f(0.0)}\tDC &Current (A)",
                  f"IACREQ\tQUANT\t{f(1e-9)}\tAC &Current (A rms)"]
    else:
        lines += [f"VDC\tPOTEN\t{f(0.0)}\tT\tDC &Voltage (V)",
                  f"VACAMPL\tQUANT\t{f(10)}\tAC &Voltage (mV rms)"]
    lines += [
        f"FREQINIT\tQUANT\t{f(freq.max())}\t&Initial Freq. (Hz)",
        f"FREQFINAL\tQUANT\t{f(freq.min())}\t&Final Freq. (Hz)",
        f"PTSPERDEC\tQUANT\t{f(ppd)}\t&Points/decade",
        f"AREA\tQUANT\t{f(area)}\t&Area (cm^2)",
        f"EOC\tQUANT\t{f(eoc)}\tOpen Circuit (V)",
    ]
    if ocv:
        lines += ["OCVCURVE\tTABLE\t5",
                  "\tPt\tT\tVf\tVm\tAch\tOver\tTemp",
                  "\t#\ts\tV vs. Ref.\tV\tV\tbits\tdeg C"]
        for i in range(5):
            v = eoc + 0.0005 * rng.standard_normal()
            lines.append(f"\t{i}\t{f(i * 0.5)}\t{f(v)}\t{f(v)}\t{f(0.0)}\t...........\t{f(25.0)}")
    lines.append(f"ZCURVE\tTABLE\t{len(freq)}" if rowcount else "ZCURVE\tTABLE")
    lines.append("\tPt\tTime\tFreq\tZreal\tZimag\tZsig\tZmod\tZphz\tIdc\tVdc\tIERange")
    lines.append("\t#\ts\tHz\tohm\tohm\tV\tohm\t°\tA\tV\t#")
    t = 0.0
    for i, (fr, zz) in enumerate(zip(freq, z_ohm)):
        t += max(1.0, 2.0 / fr)
        lines.append("\t" + "\t".join([
            str(i), f(t), f(fr), f(zz.real), f(zz.imag), f(1.0), f(abs(zz)),
            f(np.degrees(np.angle(zz))), f(1e-9), f(eoc), "10"]))
    lines.append("EXPERIMENTABORTED\tTOGGLE\tF\tExperiment Aborted")
    path.write_bytes((eol.join(lines) + eol).encode(encoding))


def make_set(folder: str, systems, freq, area, seed, noise, ppd):
    out = HERE / folder / "data"
    out.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(seed)
    for k, (fname, circ, params, eoc, opts) in enumerate(systems):
        z = Circuit(circ).impedance(params, freq) / area  # raw instrument ohms
        sig = noise(freq, np.abs(z)) * np.abs(z)
        z = z + sig * (rng.standard_normal(len(z)) + 1j * rng.standard_normal(len(z)))
        write_dta(out / fname, freq, z, eoc, rng, area=area, minute=k * 7, ppd=ppd, **opts)
        print("wrote", out / fname)


def main():
    make_set("inhibitor", INHIBITOR, np.logspace(5, -2, 71), 1.0, 42,
             lambda f, zm: np.full_like(f, 0.004), 10)
    # High-impedance data get noisier at low frequency and above ~100 MΩ.
    make_set("coating", COATING, np.logspace(5, -2, 50), COATING_AREA, 7,
             lambda f, zm: 0.004 + 0.006 * (zm > 1e8) + 0.004 * (f < 0.1), 7)


if __name__ == "__main__":
    main()
